package codemode

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bilal-arikan/tionharness/internal/mcp"
)

// bridgePy is the shared dispatcher module every generated server module
// imports. It reads the per-execution bridge URL/token from the environment
// variables the run_code tool sets on the subprocess (they exist ONLY inside a
// run_code execution) and raises MCPError on any failure — a failed MCP call
// must fail loudly in the script, never be swallowed.
const bridgePy = `# Generated by TionHarness code-execution mode (_Docs/44-CODE-EXECUTION-MCP.md).
# Regenerated on every run_code call - do not edit.
import json
import os
import urllib.error
import urllib.request


class MCPError(RuntimeError):
    """Raised when an MCP tool call fails (tool error or bridge rejection)."""


def call(tool, args):
    """Invoke a namespaced MCP tool ("server__tool") via the TionHarness bridge.

    Returns the tool's text result, JSON-decoded when possible. Raises
    MCPError on failure. Only works inside a run_code execution (the bridge
    URL/token env vars are set on the subprocess, nowhere else).
    """
    url = os.environ.get("TIONHARNESS_MCP_BRIDGE_URL")
    token = os.environ.get("TIONHARNESS_MCP_BRIDGE_TOKEN")
    if not url or not token:
        raise MCPError("MCP bridge unavailable: run this script via the run_code tool")
    body = json.dumps({"tool": tool, "args": args or {}}).encode("utf-8")
    req = urllib.request.Request(
        url + "/call",
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer " + token,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=125) as resp:
            out = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")
        raise MCPError("bridge rejected %s: HTTP %s %s" % (tool, e.code, detail)) from None
    if out.get("isError"):
        raise MCPError("%s failed: %s" % (tool, out.get("text", "")))
    text = out.get("text", "")
    try:
        return json.loads(text)
    except (ValueError, TypeError):
        return text
`

// BuiltinServer is the reserved module/namespace under which TionHarness's own
// built-in tools (not MCP tools) are exposed in the binding tree. A binding
// function calls _bridge.call("tionharness__<tool>", args); the bridge recognises the
// prefix and routes to the built-in dispatcher instead of the MCP pool. A real
// MCP server that sanitises to this same name is renamed (collision guard below),
// so the namespace stays unambiguous.
const BuiltinServer = "tionharness"

// BuiltinDef describes one TionHarness built-in tool to expose in code mode: its bare
// name, description and JSON input schema. Kept minimal (no providers import) so
// codemode stays decoupled from the tools/agent layers.
type BuiltinDef struct {
	Name        string
	Description string
	InputSchema json.RawMessage
}

// pyKeywords are Python reserved words a generated identifier must not shadow.
var pyKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

// pyIdent converts an arbitrary MCP server/tool name into a safe Python
// identifier: invalid characters become "_", a leading digit gains a "_"
// prefix, and keywords gain a "_" suffix.
func pyIdent(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	id := b.String()
	if id == "" {
		id = "_"
	}
	if id[0] >= '0' && id[0] <= '9' {
		id = "_" + id
	}
	if pyKeywords[id] {
		id += "_"
	}
	return id
}

// escapeDocstring makes a tool description safe inside a `"""` docstring.
func escapeDocstring(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"""`, `\"\"\"`)
	return s
}

// WriteBindings renders the Python binding tree into dir: the shared _bridge.py
// dispatcher, one module per MCP server, plus a single `tionharness` module for the
// exposed TionHarness built-in tools. dir is recreated from scratch on every call (it
// is a dedicated, generated-only directory) so removed servers/tools never linger.
// allow filters by name (nil = allow all) — the SAME predicate the agent's native
// tool loop uses, so the binding tree never advertises a tool the agent could not
// call directly. MCP entries are filtered by their namespaced name, built-ins by
// their bare name. Returns module -> function names, sorted.
func WriteBindings(dir string, entries []mcp.CatalogEntry, builtins []BuiltinDef, allow func(string) bool) (map[string][]string, error) {
	if err := os.RemoveAll(dir); err != nil {
		return nil, fmt.Errorf("codemode: clear bindings dir: %w", err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("codemode: create bindings dir: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "_bridge.py"), []byte(bridgePy), 0o644); err != nil {
		return nil, fmt.Errorf("codemode: write _bridge.py: %w", err)
	}

	modules := map[string][]string{}

	// Group the MCP catalog by server, respecting the allow filter.
	byServer := map[string][]mcp.CatalogEntry{}
	for _, e := range entries {
		if allow != nil && !allow(e.NamespacedName) {
			continue
		}
		byServer[e.Server] = append(byServer[e.Server], e)
	}
	for server, list := range byServer {
		module := pyIdent(server)
		switch module {
		case "_bridge":
			module = "_bridge_server" // never collide with the dispatcher module
		case BuiltinServer:
			module = BuiltinServer + "_server" // never collide with the built-ins module
		}
		src, funcs := renderServerModule(server, module, list)
		if err := os.WriteFile(filepath.Join(dir, module+".py"), []byte(src), 0o644); err != nil {
			return nil, fmt.Errorf("codemode: write module %s: %w", module, err)
		}
		modules[module] = funcs
	}

	// TionHarness built-in tools: one `tionharness` module, dispatched under the reserved
	// BuiltinServer namespace. Filtered by bare name (same agent tool filter).
	var picked []BuiltinDef
	for _, b := range builtins {
		if allow != nil && !allow(b.Name) {
			continue
		}
		picked = append(picked, b)
	}
	if len(picked) > 0 {
		src, funcs := renderBuiltinModule(picked)
		if err := os.WriteFile(filepath.Join(dir, BuiltinServer+".py"), []byte(src), 0o644); err != nil {
			return nil, fmt.Errorf("codemode: write module %s: %w", BuiltinServer, err)
		}
		modules[BuiltinServer] = funcs
	}
	return modules, nil
}

// renderBuiltinModule renders the `tionharness` module wrapping the exposed built-in
// tools, one function each, dispatched via the reserved BuiltinServer namespace.
func renderBuiltinModule(list []BuiltinDef) (string, []string) {
	sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by TionHarness code-execution mode: the TionHarness BUILT-IN tools.\n")
	b.WriteString("# Regenerated on every run_code call - do not edit. Each function wraps one\n")
	b.WriteString("# built-in tool (the same tools the agent can call directly): pass arguments\n")
	b.WriteString("# as keywords matching its input schema; the return value is the tool's text\n")
	b.WriteString("# result, JSON-decoded when possible. Raises _bridge.MCPError on failure.\n")
	b.WriteString("import _bridge\n")

	taken := map[string]bool{}
	var funcs []string
	for _, e := range list {
		fn := pyIdent(e.Name)
		for i := 2; taken[fn]; i++ {
			fn = fmt.Sprintf("%s_%d", pyIdent(e.Name), i)
		}
		taken[fn] = true
		funcs = append(funcs, fn)

		schema, err := json.MarshalIndent(json.RawMessage(mcp.NormalizeSchema(e.InputSchema)), "    ", "  ")
		if err != nil {
			schema = []byte("{}")
		}
		b.WriteString("\n\n")
		fmt.Fprintf(&b, "def %s(**args):\n", fn)
		fmt.Fprintf(&b, "    \"\"\"%s\n\n", escapeDocstring(strings.TrimSpace(e.Description)))
		fmt.Fprintf(&b, "    TionHarness built-in tool: %s\n", e.Name)
		fmt.Fprintf(&b, "    Input schema:\n    %s\n", escapeDocstring(string(schema)))
		b.WriteString("    \"\"\"\n")
		fmt.Fprintf(&b, "    return _bridge.call(%q, args)\n", BuiltinServer+"__"+e.Name)
	}
	sort.Strings(funcs)
	return b.String(), funcs
}

// renderServerModule renders one server's Python module and returns its source
// plus the sorted function names it defines. Function-name collisions after
// sanitisation get a numeric suffix so every tool stays reachable.
func renderServerModule(server, module string, list []mcp.CatalogEntry) (string, []string) {
	sort.Slice(list, func(i, j int) bool { return list[i].Tool.Name < list[j].Tool.Name })

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by TionHarness code-execution mode from MCP server %q.\n", server)
	b.WriteString("# Regenerated on every run_code call - do not edit. Each function wraps one\n")
	b.WriteString("# MCP tool: pass arguments as keywords matching its input schema; the return\n")
	b.WriteString("# value is the tool's text result, JSON-decoded when possible. Raises\n")
	b.WriteString("# _bridge.MCPError on failure.\n")
	b.WriteString("import _bridge\n")

	taken := map[string]bool{}
	var funcs []string
	for _, e := range list {
		fn := pyIdent(e.Tool.Name)
		for i := 2; taken[fn]; i++ {
			fn = fmt.Sprintf("%s_%d", pyIdent(e.Tool.Name), i)
		}
		taken[fn] = true
		funcs = append(funcs, fn)

		schema, err := json.MarshalIndent(json.RawMessage(mcp.NormalizeSchema(e.Tool.InputSchema)), "    ", "  ")
		if err != nil {
			schema = []byte("{}")
		}
		b.WriteString("\n\n")
		fmt.Fprintf(&b, "def %s(**args):\n", fn)
		fmt.Fprintf(&b, "    \"\"\"%s\n\n", escapeDocstring(strings.TrimSpace(e.Tool.Description)))
		fmt.Fprintf(&b, "    MCP tool: %s\n", e.NamespacedName)
		fmt.Fprintf(&b, "    Input schema:\n    %s\n", escapeDocstring(string(schema)))
		b.WriteString("    \"\"\"\n")
		fmt.Fprintf(&b, "    return _bridge.call(%q, args)\n", e.NamespacedName)
	}
	sort.Strings(funcs)
	return b.String(), funcs
}
