package tools

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
)

// flexBool is a bool that also accepts the shapes a model actually emits.
//
// Tool arguments are generated by an LLM, not by a typed client, and models
// routinely quote booleans: `"no_compress": "true"` instead of `true`. Strict
// decoding rejects the whole call with "cannot unmarshal string into Go struct
// field ... of type bool", and the model has to guess what went wrong.
//
// That failure was observed at the worst possible moment (2026-07-31): a shell
// command had failed, the optimizer note told the agent to re-run with
// `no_compress: true` to recover the raw output, the agent did exactly that — and
// the call was refused over the quoting. The escape hatch broke precisely when it
// was needed, costing two extra round-trips.
//
// Only unambiguous spellings are accepted. A value that does not clearly mean
// true or false is still an error: silently reading "maybe" as false would trade a
// visible failure for an invisible one.
//
// Mirrors the flexOptions/askOption precedent in builtin_ask.go.
type flexBool bool

func (b *flexBool) UnmarshalJSON(data []byte) error {
	data = bytes.TrimSpace(data)
	// A JSON null leaves the field at its zero value, like an absent key.
	if bytes.Equal(data, []byte("null")) {
		return nil
	}
	// The correct shape first, so the common path stays cheap.
	var native bool
	if err := json.Unmarshal(data, &native); err == nil {
		*b = flexBool(native)
		return nil
	}
	// A quoted spelling: "true", "false", "1", "0", "yes", "no", …
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		switch v, perr := strconv.ParseBool(s); {
		case perr == nil:
			*b = flexBool(v)
			return nil
		case s == "yes" || s == "on":
			*b = true
			return nil
		case s == "no" || s == "off" || s == "":
			*b = false
			return nil
		}
		return fmt.Errorf("expected a boolean, got %q (use true or false)", s)
	}
	// A bare number: 1 / 0, which some models emit for flags.
	var n float64
	if err := json.Unmarshal(data, &n); err == nil && (n == 0 || n == 1) {
		*b = n == 1
		return nil
	}
	return fmt.Errorf("expected a boolean, got %s (use true or false)", data)
}
