#!/usr/bin/env bash
# TionHarness installer for Linux, macOS and Git Bash on Windows.
#
# Usage:
#   bash scripts/install.sh
#
# Environment:
#   TIONHARNESS_FEED_URL      release feed base URL (default https://dl.tionharness.com)
#   TIONHARNESS_INSTALL_DIR   install directory (default $HOME/.local/bin)
set -euo pipefail

feed_url=${TIONHARNESS_FEED_URL:-https://dl.tionharness.com}
feed_url=${feed_url%/}
binary=tionharness

fail() {
  printf 'install: %s\n' "$1" >&2
  exit 1
}

work_dir=
cleanup() {
  if [ -n "$work_dir" ] && [ -d "$work_dir" ]; then
    rm -rf "$work_dir"
  fi
}
trap cleanup EXIT INT TERM

# --- required tools -----------------------------------------------------------

if command -v curl >/dev/null 2>&1; then
  fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  fetch() { wget -q -O "$2" "$1"; }
else
  fail "required tool not found: curl or wget"
fi

if command -v sha256sum >/dev/null 2>&1; then
  sha256_of() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
  sha256_of() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
  fail "required tool not found: sha256sum or shasum"
fi

# --- platform detection -------------------------------------------------------

case "$(uname -s)" in
  Linux) host_os=linux ;;
  Darwin) host_os=darwin ;;
  MINGW* | MSYS* | CYGWIN* | Windows_NT) host_os=windows ;;
  *) fail "unsupported operating system: $(uname -s)" ;;
esac

case "$(uname -m)" in
  x86_64 | amd64) host_arch=amd64 ;;
  aarch64 | arm64) host_arch=arm64 ;;
  *) fail "unsupported architecture: $(uname -m)" ;;
esac

if [ "$host_os" = windows ]; then
  binary=tionharness.exe
fi

# --- feed ---------------------------------------------------------------------

work_dir=$(mktemp -d 2>/dev/null || mktemp -d -t tionharness)
feed_file="$work_dir/latest.json"

printf 'Fetching %s/latest.json\n' "$feed_url"
fetch "$feed_url/latest.json" "$feed_file" || fail "failed to download $feed_url/latest.json"

# Read a string field out of a JSON fragment. Deliberately minimal: the feed
# schema is flat and generated by scripts/build-release.sh.
json_string() {
  printf '%s' "$1" | sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1
}

feed_body=$(tr -d '\n\r' <"$feed_file")
version=$(json_string "${feed_body%%\"artifacts\"*}" version)
[ -n "$version" ] || fail "malformed feed: no version field in $feed_url/latest.json"

# Split the artifact array into one object per line so each can be matched.
artifact=$(
  printf '%s' "$feed_body" |
    sed 's/},/}\n/g' |
    grep '"os"[[:space:]]*:[[:space:]]*"'"$host_os"'"' |
    grep '"arch"[[:space:]]*:[[:space:]]*"'"$host_arch"'"' |
    head -n 1
) || true

if [ -z "$artifact" ]; then
  fail "no release artifact for $host_os/$host_arch in $feed_url/latest.json (version $version)"
fi

artifact_file=$(json_string "$artifact" file)
artifact_url=$(json_string "$artifact" url)
artifact_sha=$(json_string "$artifact" sha256)

[ -n "$artifact_file" ] || fail "malformed artifact entry for $host_os/$host_arch: no file field"
[ -n "$artifact_url" ] || fail "malformed artifact entry for $host_os/$host_arch: no url field"
[ -n "$artifact_sha" ] || fail "malformed artifact entry for $host_os/$host_arch: no sha256 field"

# --- download and verify ------------------------------------------------------

archive="$work_dir/$artifact_file"
printf 'Downloading %s\n' "$artifact_url"
fetch "$artifact_url" "$archive" || fail "failed to download $artifact_url"

actual_sha=$(sha256_of "$archive")
if [ "$actual_sha" != "$artifact_sha" ]; then
  rm -f "$archive"
  printf 'install: checksum mismatch for %s\n' "$artifact_file" >&2
  printf 'install:   expected %s\n' "$artifact_sha" >&2
  printf 'install:   actual   %s\n' "$actual_sha" >&2
  printf 'install: the download was deleted and nothing was installed\n' >&2
  exit 1
fi
printf 'Checksum OK (%s)\n' "$artifact_sha"

# --- extract ------------------------------------------------------------------

extract_dir="$work_dir/extract"
mkdir -p "$extract_dir"

case "$artifact_file" in
  *.tar.gz | *.tgz)
    command -v tar >/dev/null 2>&1 || fail "required tool not found: tar"
    tar -xzf "$archive" -C "$extract_dir"
    ;;
  *.zip)
    if command -v unzip >/dev/null 2>&1; then
      unzip -q -o "$archive" -d "$extract_dir"
    elif command -v powershell >/dev/null 2>&1; then
      powershell -NoProfile -Command "Expand-Archive -LiteralPath '$archive' -DestinationPath '$extract_dir' -Force"
    else
      fail "required tool not found: unzip (needed to extract $artifact_file)"
    fi
    ;;
  *)
    fail "unsupported archive format: $artifact_file"
    ;;
esac

extracted="$extract_dir/$binary"
[ -f "$extracted" ] || fail "archive $artifact_file does not contain $binary"

# --- install ------------------------------------------------------------------

install_dir=${TIONHARNESS_INSTALL_DIR:-$HOME/.local/bin}
mkdir -p "$install_dir" || fail "cannot create install directory: $install_dir"

target="$install_dir/$binary"
cp "$extracted" "$target" || fail "cannot write $target"
chmod +x "$target"

printf 'Installed tionharness %s to %s\n' "$version" "$target"

case ":$PATH:" in
  *":$install_dir:"*) ;;
  *)
    printf '\n%s is not on your PATH. Add it by appending this line to your shell rc file\n' "$install_dir"
    printf '(~/.bashrc, ~/.zshrc, ...) and opening a new shell:\n\n'
    printf '    export PATH="%s:$PATH"\n\n' "$install_dir"
    ;;
esac
