// Curated emoji dataset for the agent avatar picker. We deliberately ship a
// self-contained, dependency-free list (rather than pulling in emoji-mart and
// its large data bundle) — a few hundred emojis grouped by category, each with
// search keywords. This keeps the bundle lean and matches the project's
// minimal-dependency ethos.

export interface EmojiEntry {
  /** The emoji character itself. */
  char: string
  /** Lowercase keywords used for substring search. */
  keywords: string
}

export interface EmojiCategory {
  /** Stable id for the category tab. */
  id: string
  /** Turkish label shown in the tab strip. */
  label: string
  /** Representative glyph for the tab button. */
  icon: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Yüzler',
    icon: '🙂',
    emojis: [
      { char: '😀', keywords: 'grin smile happy face' },
      { char: '😃', keywords: 'smile happy face' },
      { char: '😄', keywords: 'smile happy laugh' },
      { char: '😁', keywords: 'grin beam happy' },
      { char: '😆', keywords: 'laugh satisfied happy' },
      { char: '😅', keywords: 'sweat laugh nervous' },
      { char: '😂', keywords: 'joy laugh tears funny' },
      { char: '🤣', keywords: 'rofl laugh funny' },
      { char: '😊', keywords: 'blush smile happy' },
      { char: '🙂', keywords: 'slight smile' },
      { char: '🙃', keywords: 'upside down silly' },
      { char: '😉', keywords: 'wink' },
      { char: '😌', keywords: 'relieved calm' },
      { char: '😍', keywords: 'heart eyes love' },
      { char: '🥰', keywords: 'love hearts adore' },
      { char: '😘', keywords: 'kiss love' },
      { char: '😎', keywords: 'cool sunglasses' },
      { char: '🤩', keywords: 'star struck excited wow' },
      { char: '🤔', keywords: 'thinking hmm' },
      { char: '🤨', keywords: 'raised eyebrow skeptic' },
      { char: '😐', keywords: 'neutral meh' },
      { char: '😴', keywords: 'sleep zzz tired' },
      { char: '😇', keywords: 'angel innocent halo' },
      { char: '🤓', keywords: 'nerd geek glasses' },
      { char: '🧐', keywords: 'monocle inspect' },
      { char: '😜', keywords: 'wink tongue silly' },
      { char: '🤯', keywords: 'mind blown explode' },
      { char: '😱', keywords: 'scream shock fear' },
      { char: '🥳', keywords: 'party celebrate hat' },
      { char: '😤', keywords: 'huff angry steam' },
      { char: '👻', keywords: 'ghost spooky boo' },
      { char: '💀', keywords: 'skull dead' },
      { char: '🤖', keywords: 'robot bot ai machine' },
      { char: '👽', keywords: 'alien ufo' },
      { char: '🎃', keywords: 'pumpkin halloween' },
      { char: '😺', keywords: 'cat smile' },
    ],
  },
  {
    id: 'people',
    label: 'İnsan',
    icon: '🧠',
    emojis: [
      { char: '🧠', keywords: 'brain mind think smart' },
      { char: '🫀', keywords: 'heart organ anatomical' },
      { char: '👀', keywords: 'eyes look watch' },
      { char: '👁️', keywords: 'eye look see' },
      { char: '👋', keywords: 'wave hand hello' },
      { char: '🤚', keywords: 'hand stop raised' },
      { char: '👍', keywords: 'thumbs up approve like' },
      { char: '👎', keywords: 'thumbs down dislike' },
      { char: '👏', keywords: 'clap applause' },
      { char: '🙌', keywords: 'raise hands celebrate' },
      { char: '🙏', keywords: 'pray thanks please' },
      { char: '🤝', keywords: 'handshake deal agree' },
      { char: '✌️', keywords: 'peace victory' },
      { char: '🤞', keywords: 'fingers crossed luck' },
      { char: '👌', keywords: 'ok perfect' },
      { char: '💪', keywords: 'muscle strong power' },
      { char: '🦾', keywords: 'mechanical arm robot strong' },
      { char: '✍️', keywords: 'writing hand write' },
      { char: '👨‍💻', keywords: 'developer coder programmer man' },
      { char: '👩‍💻', keywords: 'developer coder programmer woman' },
      { char: '🕵️', keywords: 'detective spy investigate' },
      { char: '🧑‍🚀', keywords: 'astronaut space' },
      { char: '🧑‍🔬', keywords: 'scientist research lab' },
      { char: '🧙', keywords: 'wizard mage magic' },
      { char: '🦸', keywords: 'superhero hero' },
      { char: '🤺', keywords: 'fencing fight' },
    ],
  },
  {
    id: 'nature',
    label: 'Doğa',
    icon: '🐝',
    emojis: [
      { char: '🐝', keywords: 'bee swarm bug honey' },
      { char: '🦉', keywords: 'owl wise bird night' },
      { char: '🐙', keywords: 'octopus tentacle' },
      { char: '🦊', keywords: 'fox clever' },
      { char: '🐺', keywords: 'wolf pack' },
      { char: '🦁', keywords: 'lion king brave' },
      { char: '🐯', keywords: 'tiger' },
      { char: '🐱', keywords: 'cat kitten' },
      { char: '🐶', keywords: 'dog puppy' },
      { char: '🐢', keywords: 'turtle slow' },
      { char: '🐬', keywords: 'dolphin sea' },
      { char: '🦈', keywords: 'shark sea' },
      { char: '🦅', keywords: 'eagle bird hawk' },
      { char: '🦋', keywords: 'butterfly' },
      { char: '🐉', keywords: 'dragon' },
      { char: '🦄', keywords: 'unicorn magic' },
      { char: '🌳', keywords: 'tree nature' },
      { char: '🌵', keywords: 'cactus desert' },
      { char: '🌸', keywords: 'flower blossom' },
      { char: '🌻', keywords: 'sunflower flower' },
      { char: '🍀', keywords: 'clover luck' },
      { char: '🔥', keywords: 'fire hot flame' },
      { char: '⭐', keywords: 'star favorite' },
      { char: '🌟', keywords: 'star glow sparkle' },
      { char: '✨', keywords: 'sparkles shiny magic' },
      { char: '⚡', keywords: 'lightning bolt fast power' },
      { char: '🌈', keywords: 'rainbow' },
      { char: '🌊', keywords: 'wave water ocean' },
      { char: '❄️', keywords: 'snow cold ice' },
      { char: '🌙', keywords: 'moon night' },
    ],
  },
  {
    id: 'objects',
    label: 'Nesne',
    icon: '⚙️',
    emojis: [
      { char: '⚙️', keywords: 'gear settings config cog' },
      { char: '🛠️', keywords: 'tools build wrench' },
      { char: '🔧', keywords: 'wrench tool fix transform' },
      { char: '🔨', keywords: 'hammer build' },
      { char: '🧰', keywords: 'toolbox tools' },
      { char: '🔩', keywords: 'bolt nut screw' },
      { char: '🔬', keywords: 'microscope science research' },
      { char: '🔭', keywords: 'telescope observe space' },
      { char: '🧪', keywords: 'test tube chemistry experiment' },
      { char: '🧬', keywords: 'dna biology gene' },
      { char: '🛰️', keywords: 'satellite space signal' },
      { char: '📡', keywords: 'antenna signal dish broadcast' },
      { char: '🔮', keywords: 'crystal ball predict magic' },
      { char: '🧭', keywords: 'compass navigate direction' },
      { char: '🗺️', keywords: 'map navigate' },
      { char: '💡', keywords: 'idea light bulb think' },
      { char: '🔦', keywords: 'flashlight search' },
      { char: '🔋', keywords: 'battery power energy' },
      { char: '🔌', keywords: 'plug power electric' },
      { char: '💻', keywords: 'laptop computer code' },
      { char: '🖥️', keywords: 'desktop computer monitor' },
      { char: '⌨️', keywords: 'keyboard type' },
      { char: '🖱️', keywords: 'mouse click' },
      { char: '💾', keywords: 'floppy save disk' },
      { char: '💿', keywords: 'disc cd data' },
      { char: '📦', keywords: 'package box deliver' },
      { char: '📁', keywords: 'folder files' },
      { char: '📄', keywords: 'document file page' },
      { char: '📊', keywords: 'chart bar stats data' },
      { char: '📈', keywords: 'chart up growth trend' },
      { char: '📉', keywords: 'chart down decline' },
      { char: '📌', keywords: 'pin marker' },
      { char: '📎', keywords: 'paperclip attach' },
      { char: '🔗', keywords: 'link chain url' },
      { char: '🔑', keywords: 'key secret unlock' },
      { char: '🔒', keywords: 'lock secure private' },
      { char: '🛡️', keywords: 'shield protect security' },
      { char: '⏰', keywords: 'alarm clock time schedule' },
      { char: '⏱️', keywords: 'stopwatch timer delay' },
      { char: '📅', keywords: 'calendar date schedule' },
      { char: '✅', keywords: 'check done complete' },
      { char: '❌', keywords: 'cross fail error no' },
      { char: '⚠️', keywords: 'warning alert caution' },
      { char: '🚀', keywords: 'rocket launch fast ship' },
    ],
  },
  {
    id: 'symbols',
    label: 'Sembol',
    icon: '🎯',
    emojis: [
      { char: '🎯', keywords: 'target goal aim dart' },
      { char: '🏆', keywords: 'trophy win award' },
      { char: '🏅', keywords: 'medal award' },
      { char: '🎖️', keywords: 'medal military honor' },
      { char: '🎲', keywords: 'dice random game' },
      { char: '🎮', keywords: 'game controller play' },
      { char: '🎨', keywords: 'art paint palette design' },
      { char: '🎭', keywords: 'theater drama mask' },
      { char: '🎬', keywords: 'movie clapper film' },
      { char: '🎵', keywords: 'music note song' },
      { char: '🔔', keywords: 'bell notify alert' },
      { char: '📣', keywords: 'megaphone announce broadcast' },
      { char: '💬', keywords: 'speech chat message bubble' },
      { char: '💭', keywords: 'thought bubble think' },
      { char: '❤️', keywords: 'heart love red' },
      { char: '🧡', keywords: 'heart orange love' },
      { char: '💛', keywords: 'heart yellow love' },
      { char: '💚', keywords: 'heart green love' },
      { char: '💙', keywords: 'heart blue love' },
      { char: '💜', keywords: 'heart purple love' },
      { char: '♻️', keywords: 'recycle loop reflect' },
      { char: '🔄', keywords: 'refresh cycle loop sync' },
      { char: '➕', keywords: 'plus add' },
      { char: '❓', keywords: 'question ask help' },
      { char: '❗', keywords: 'exclamation important' },
      { char: '💯', keywords: 'hundred perfect score' },
      { char: '🆕', keywords: 'new badge' },
      { char: '🔢', keywords: 'numbers count' },
      { char: '🔠', keywords: 'letters abc text' },
      { char: '♠️', keywords: 'spade card' },
      { char: '♥️', keywords: 'hearts card' },
      { char: '♦️', keywords: 'diamond card' },
      { char: '♣️', keywords: 'club card' },
    ],
  },
]

// flatEmojis is the full list across all categories, used for global search.
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)

// searchEmojis returns entries whose char or keywords contain the query.
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return ALL_EMOJIS
  return ALL_EMOJIS.filter((e) => e.char === q || e.keywords.includes(q))
}
