import type { Message, TurnStep } from '@/types'
import { extractFileChanges } from '@/shared/lib/fileChanges'

// <task-notification> envelope parser. Split out so TaskNotificationNote.tsx
// exports only components (fast refresh).
interface ParsedNotification {
  taskId: string
  agentId: string
  agent: string
  model: string
  status: string
  summary: string
  result: string
  toolUses: string
  durationMs: string
  source: string
}

// tagText extracts the inner text of the FIRST <tag>...</tag> occurrence. The
// notification format is generated by the backend (formatTaskNotification), so a
// lightweight regex is sufficient — no need for a real XML parser. `result` may
// span many lines, hence the s-flag equivalent via [\s\S].
function tagText(text: string, tag: string): string {
  const m = text.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`))
  return m
    ? m[1]
        .trim()
        .replace(
          /&(amp|lt|gt|quot|#34|#39);/g,
          (_, entity: string) =>
            ({ amp: '&', lt: '<', gt: '>', quot: '"', '#34': '"', '#39': "'" })[entity] ?? _,
        )
    : ''
}

// parseTaskNotification pulls the display fields out of a <task-notification>
// block. Returns null when the text doesn't look like one (caller falls back to
// raw rendering).
export function parseTaskNotification(text: string): ParsedNotification | null {
  if (!text.trimStart().startsWith('<task-notification>')) return null
  return {
    taskId: tagText(text, 'task-id'),
    agentId: tagText(text, 'agent-id'),
    agent: tagText(text, 'agent'),
    model: tagText(text, 'model'),
    status: tagText(text, 'status'),
    summary: tagText(text, 'summary'),
    result: tagText(text, 'result'),
    toolUses: tagText(text, 'tool_uses'),
    durationMs: tagText(text, 'duration_ms'),
    source: tagText(text, 'source'),
  }
}

export function notificationChanges(stepsJSON?: string): TurnStep[] {
  if (!stepsJSON) return []
  const steps: TurnStep[] = JSON.parse(stepsJSON)
  return extractFileChanges(steps).map((change) => ({
    kind: 'diff',
    tool: change.tool,
    path: change.path,
    patch: change.patch,
    added: change.added,
    removed: change.removed,
    created: change.created,
    patchTruncated: change.truncated,
  }))
}

// Keep the original report visible while pointing readers to later outcomes.
// A worker session can be reused, so a later failure does not rewrite history.
export function laterNotificationStatuses(messages: Message[]): Map<string, string> {
  const latest = new Map<string, string>()
  const later = new Map<string, string>()
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]
    if (message.origin !== 'worker-note') continue
    const parsed = parseTaskNotification(message.text)
    if (!parsed?.taskId) continue
    const status = latest.get(parsed.taskId)
    if (status) later.set(message.id, status)
    else latest.set(parsed.taskId, parsed.status)
  }
  return later
}
